In [2]:
import numpy as np

Create a 10x50 matrix with random numbers using numpy

In [5]:
x = np.random.rand(10,50)
# Print the shape of the matrix
print(x.shape)

(10, 50)


In [6]:
# Ask from the user for a row number and print the row given
row = int(input("Enter a row number: "))
print(x[row])
# Do the same for a column
col = int(input("Enter a column number: "))
print(x[:,col])

[0.23987495 0.91661312 0.86479877 0.97246676 0.2996044  0.19370428
 0.38302033 0.45876654 0.23953333 0.88275397 0.39823726 0.68814433
 0.69320487 0.87894669 0.12043348 0.56381261 0.41057224 0.44619567
 0.83936425 0.11512131 0.10305665 0.30666838 0.10695437 0.77828681
 0.26825193 0.88529244 0.13623807 0.85569497 0.56312584 0.83247308
 0.4950099  0.66125172 0.45603826 0.41389193 0.04471278 0.74099649
 0.82862858 0.73879875 0.10928491 0.47473116 0.1124304  0.02034965
 0.3651702  0.24298615 0.02315607 0.63034624 0.86772443 0.45138212
 0.68984731 0.45618784]


Create the following arrays and calculate their dot product
| 5 | 1 | 3 |
| 1 | 2 | 1 |
| 1 | 2 | 1 |

| 1 | 2 | 3 |

In [9]:
tmp_array = np.array([[5,1,3],[1,2,1],[1,2,1]])
tmp_array2 = np.array([1,2,3])
print(tmp_array)
print(tmp_array2)
# print dot product of tmp_array and tmp_array2
print(np.dot(tmp_array,tmp_array2))

[[5 1 3]
 [1 2 1]
 [1 2 1]]
[1 2 3]
[16  8  8]


Given the following matrices calculate their (matrix) multiplication
A = | 1 | 0 |
| 0 | 1 |

B = | 4 | 1 |
| 2 | 2 |

c = | 1 | 2 |

In [11]:
# A*B
A = np.array([[1,0],[0,1]])
B = np.array([[4,1],[2,2]])
print(np.dot(A,B))
# A*c
c = np.array([1,2])
print(np.dot(A,c.T))

[[4 1]
 [2 2]]
[1 2]


Find the third power of this matrix

| 0 | 1 |
| -1 | 0 |

In [ ]:
tmp_array = np.array([[0,1],[-1,0]])
print(np.linalg.matrix_power(tmp_array,3))

Find the determinant of this matrix

| 1 | 2 |
| 3 | 4 |

In [10]:
tmp_array = np.array([[1,2],[3,4]])
print(np.linalg.det(tmp_array))

-2.0000000000000004


Use the functions ‘eye’ and ‘ones’ from numpy to create 4x4 matrices. Find their ranks.

In [12]:
tmp_array = np.eye(4)
print(tmp_array)
print(np.linalg.matrix_rank(tmp_array))
tmp_array = np.ones((4,4))
print(tmp_array)
print(np.linalg.matrix_rank(tmp_array))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1


Find the inverse of this matrix

| 2 | 2 | 1 |
| 1 | 3 | 1 |
| 1 | 2 | 2 |

In [13]:
tmp_array = np.array([[2,2,1],[1,3,1],[1,2,2]])
print(np.linalg.inv(tmp_array))

[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


Find the pseudo inverse of this matrix

| 2 | 8 |
| 1 | 4 |

In [14]:
tmp_array = np.array([[2,8],[1,4]])
print(np.linalg.pinv(tmp_array))

[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


Find the eigenvalues and eigenvectors of this matrix

| 1 | -1 |
| 1 | 1 |

In [15]:
tmp_array = np.array([[1,-1],[1,1]])
eigenvalues, eigenvectors = np.linalg.eig(tmp_array)
print(eigenvalues)
print(eigenvectors)


[1.+1.j 1.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
